# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shopimize' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shopimize

	pod 'GoogleMaps', '6.0.1'

  target 'shopimizeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shopimizeUITests' do
    # Pods for testing
  end

end
