# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'shopimize' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for shopimize

	pod 'GoogleMaps', '6.0.1'
	pod 'Firebase/Auth'
	pod 'FirebaseFirestoreSwift', '> 7.0-beta'
#pod 'Firebase/Firestore'

  target 'shopimizeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shopimizeUITests' do
    # Pods for testing
  end

end
